#!/bin/bash
int='^[0-9]+$'
SUM=0
for i in "$@"; do
      if [[ $i =~ $int ]]; then
        let SUM+=$i
      else
        echo "please, enter number only"
        exit 1
      fi
done
echo "Sum: $SUM"
echo "Args number: $#"
let x=$SUM/$#
echo "Result: $x"
